---
deployment:
  tasks:
    - export DEPLOYPATH=/home/user/jaynilhosieryworks.com/
    - /bin/cp index.html $DEPLOYPATH
    # - /bin/cp style.css $DEPLOYPATH
    - /bin/cp /css/style.css $DEPLOYPATH
